#! /bin/python

from os import path, makedirs
from sys import argv

from load import readMultiAST
from template import renderStructs

if len(argv) < 3:
    print("Usage: ")
    print("lua-json-serde <outputdir> <config1> <config2> ...")
    exit(0)

outputDir = argv[1]
configs = argv[2:]

if not path.exists(outputDir):
    makedirs(outputDir)

astList = readMultiAST(configs)
generatedFiles = []

for ast in astList:
    render = renderStructs(ast)

    filename = ast['filename'] + '.hpp'
    generatedFiles.append(filename)

    file = open(path.join(outputDir, filename), 'w')
    file.write(render)
    file.close()

file = open(path.join(outputDir, 'include_all.hpp'), 'w')
file.writelines(['#include "' + filename + '"\n' for filename in generatedFiles])
file.close()




